'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { apiFetch, type ContentReview, type ContentVersion, type PaginatedResult, type ReviewableContent } from '@danvic/api-client'
import { Badge, Button, Field, FormMessage, Input, PageHeader } from '@danvic/ui'

const date = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-NG') : '—'
const status = (item: Pick<ReviewableContent, 'reviewStatus' | 'publicationStatus'>) => item.publicationStatus === 'archived' ? 'Archived' : item.publicationStatus === 'published' ? 'Published' : item.reviewStatus === 'approved' ? 'Approved' : item.reviewStatus === 'pending_review' ? 'Pending review' : item.reviewStatus === 'needs_revision' ? 'Needs revision' : item.reviewStatus === 'rejected' ? 'Rejected' : 'Draft'
const tone = (value: string) => value === 'Published' || value === 'Approved' ? 'green' : value === 'Rejected' ? 'red' : value === 'Needs revision' ? 'amber' : value === 'Pending review' ? 'violet' : 'blue'
const errorCode = (cause: unknown) => (cause as { code?: string })?.code ?? ''

export function ReviewStatusBadge({ value }: { value: Pick<ReviewableContent, 'reviewStatus' | 'publicationStatus'> }) { const label = status(value); return <Badge dot tone={tone(label)}>{label}</Badge> }

export function VersionHistory({ versions }: { versions: ContentVersion[] }) { return versions.length ? <div className="sb-table-wrap"><table className="sb-table"><thead><tr><th>Version</th><th>State</th><th>Created by</th><th>Updated</th><th>Changes</th></tr></thead><tbody>{versions.map((version) => <tr key={version.id}><td>{version.label || `v${version.number}`}</td><td>{version.state}</td><td>{version.createdBy.firstName} {version.createdBy.lastName}</td><td>{date(version.updatedAt)}</td><td>{version.changeSummary ?? '—'}</td></tr>)}</tbody></table></div> : <p className="ad-empty-line">No versions recorded yet.</p> }

export function ReviewFeedbackPanel({ reviews }: { reviews: ContentReview[] }) { return <section className="ad-section"><div className="ad-section-heading"><div><h2>Review feedback</h2><p>Scores and comments returned by the reviewer.</p></div></div>{reviews.length ? reviews.map((review) => <article className="ad-review-record" key={review.id}><div><Badge>{review.decision.replace(/_/g, ' ')}</Badge><span>{review.reviewer.firstName} {review.reviewer.lastName} · {date(review.createdAt)}</span></div><p>{review.summary}</p><ul>{review.criteria.map((criterion) => <li key={criterion.criterion}>{criterion.criterion.replace(/_/g, ' ')}: {criterion.score ?? '—'} · {criterion.comment ?? 'No comment'}</li>)}</ul></article>) : <p className="ad-empty-line">No review feedback yet.</p>}</section> }

export function SubmitForReviewDialog({ content, onDone }: { content: ReviewableContent; onDone: () => void }) { return <GovernanceAction content={content} endpoint={content.reviewStatus === 'needs_revision' ? 'resubmit' : 'submit'} label={content.reviewStatus === 'needs_revision' ? 'Resubmit revision' : 'Submit for review'} onDone={onDone} /> }

export function ControlledUpdateDialog({ content, onDone }: { content: ReviewableContent; onDone: () => void }) { return <GovernanceAction content={content} endpoint="controlled-update" label="Create controlled update" onDone={onDone} /> }

function GovernanceAction({ content, endpoint, label, onDone }: { content: ReviewableContent; endpoint: 'submit' | 'resubmit' | 'controlled-update'; label: string; onDone: () => void }) {
  const [open, setOpen] = useState(false); const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async () => { setBusy(true); setError(''); try { await apiFetch(`/api/content-governance/${encodeURIComponent(content.id)}/${endpoint}`, { method: 'POST', body: JSON.stringify(endpoint === 'controlled-update' ? { sourceVersionId: content.currentVersion?.id, changeSummary: note } : { versionId: content.currentVersion?.id ?? null, submissionNote: note }) }); setOpen(false); setNote(''); onDone() } catch (cause) { setError(errorCode(cause) === 'PUBLISHED_VERSION_IMMUTABLE' ? 'Published versions cannot be edited. Create a controlled update draft.' : cause instanceof Error ? cause.message : 'The request could not be completed.') } finally { setBusy(false) } }
  return <div className="ad-governance-action"><Button onClick={() => setOpen(true)}>{label}</Button>{open ? <div className="ad-inline-dialog" role="dialog" aria-label={label}><Field label={endpoint === 'controlled-update' ? 'Change summary' : 'Submission note'} required={endpoint === 'controlled-update'}><textarea rows={4} value={note} onChange={(event) => setNote(event.target.value)} placeholder={endpoint === 'controlled-update' ? 'Describe the controlled update' : 'Tell the reviewer what changed'} /></Field><div><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button busy={busy} onClick={() => void submit()}>{label}</Button></div><FormMessage>{error}</FormMessage></div> : null}</div>
}

function ContentRows({ items }: { items: ReviewableContent[] }) { return items.length ? <div className="sb-table-wrap"><table className="sb-table"><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Updated</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link href={`/content-review/${encodeURIComponent(item.id)}`}>{item.title}</Link><small className="ad-table-subline">{item.courseName ?? 'No course'}</small></td><td>{item.type}</td><td><ReviewStatusBadge value={item} /></td><td>{date(item.updatedAt)}</td></tr>)}</tbody></table></div> : <p className="ad-empty-line">No content matches your filters.</p> }

export function ContentReviewDashboard() {
  const [search, setSearch] = useState(''); const [result, setResult] = useState<PaginatedResult<ReviewableContent> | null>(null); const [error, setError] = useState<unknown>(null)
  const path = useMemo(() => `/api/content-governance/mine?status=&type=&search=${encodeURIComponent(search)}&page=1&limit=25`, [search])
  useEffect(() => { void apiFetch<PaginatedResult<ReviewableContent>>(path).then(setResult).catch(setError) }, [path])
  if (error) return <p className="ad-empty-line" data-tone="error">{error instanceof Error ? error.message : 'Could not load your content status.'}</p>
  const counts = result?.items.reduce<Record<string, number>>((all, item) => { const value = status(item); all[value] = (all[value] ?? 0) + 1; return all }, {}) ?? {}
  return <div className="ad-directory-page"><PageHeader title="My content status" description="Track draft, review, feedback, approval and publication state for every item you create." /><section className="ad-section ad-section--plain"><div className="ad-directory-grid">{['Draft', 'Pending review', 'Needs revision', 'Approved', 'Published', 'Rejected', 'Archived'].map((label) => <div className="ad-directory-card" key={label}><span className="ad-directory-card-label">{label}</span><strong>{counts[label] ?? 0}</strong></div>)}</div></section><section className="ad-section"><div className="ad-section-heading"><div><h2>All my content</h2><p>{result?.page.total ?? '—'} records</p></div><Input placeholder="Search content" value={search} onChange={(event) => setSearch(event.target.value)} /></div>{result ? <ContentRows items={result.items} /> : <p className="ad-empty-line">Loading content status…</p>}</section></div>
}

export function ContentReviewDetail({ contentId, update = false }: { contentId: string; update?: boolean }) {
  const [data, setData] = useState<{ content: ReviewableContent; reviews: ContentReview[]; versions: ContentVersion[]; capabilities?: Record<string, boolean> } | null>(null); const [error, setError] = useState<unknown>(null)
  useEffect(() => { void apiFetch<typeof data>(`/api/content-governance/${encodeURIComponent(contentId)}`).then(setData).catch(setError) }, [contentId])
  if (error) return <p className="ad-empty-line" data-tone="error">{errorCode(error) === 'FORBIDDEN' ? 'You do not have access to this content.' : error instanceof Error ? error.message : 'Could not load content detail.'}</p>
  if (!data) return <p className="ad-empty-line">Loading content detail…</p>
  const { content } = data; const reload = () => { void apiFetch<typeof data>(`/api/content-governance/${encodeURIComponent(contentId)}`).then(setData).catch(setError) }
  const editable = content.reviewStatus === 'draft' || content.reviewStatus === 'needs_revision'
  return <div className="ad-directory-page"><Link className="ad-course-back" href="/content-review">Back to my content</Link><PageHeader title={content.title} description={`${content.type} · ${content.courseName ?? 'No course'}`} actions={<ReviewStatusBadge value={content} />} />{update ? <section className="ad-section ad-section--plain"><h2>Controlled update draft</h2><p>The live published snapshot remains unchanged until an authorized review and publication.</p><ControlledUpdateDialog content={content} onDone={reload} /></section> : null}<section className="ad-section ad-section--plain"><div className="ad-detail-grid"><div><span className="ad-directory-card-label">Current version</span><strong>{content.currentVersion.label || `v${content.currentVersion.number}`}</strong></div><div><span className="ad-directory-card-label">Submitted</span><strong>{date(content.submittedAt)}</strong></div><div><span className="ad-directory-card-label">Approved</span><strong>{date(content.approvedAt)}</strong></div><div><span className="ad-directory-card-label">Published</span><strong>{date(content.publishedAt)}</strong></div></div>{editable && data.capabilities?.submit !== false ? <SubmitForReviewDialog content={content} onDone={reload} /> : null}{content.publicationStatus === 'published' && data.capabilities?.controlledUpdate !== false ? <ControlledUpdateDialog content={content} onDone={reload} /> : null}{content.reviewStatus === 'approved' ? <p className="ad-form-callout">Approved — awaiting publication. It is not student-visible until published.</p> : null}</section><ReviewFeedbackPanel reviews={data.reviews} /><section className="ad-section"><div className="ad-section-heading"><div><h2>Version history</h2><p>Drafts and published snapshots remain separately auditable.</p></div><Link href={`/content-review/${encodeURIComponent(contentId)}/versions`}>Open full history</Link></div><VersionHistory versions={data.versions} /></section></div>
}

export function AuthorQuestionBank() { const [items, setItems] = useState<Array<Record<string, unknown>>>([]); const [error, setError] = useState(''); const [prompt, setPrompt] = useState(''); const [busy, setBusy] = useState(false); const load = () => { void apiFetch<{ items?: Array<Record<string, unknown>> }>('/api/question-bank').then((result) => setItems(result.items ?? [])).catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not load question bank.')) }; useEffect(load, [])
  const create = async () => { if (!prompt.trim()) return; setBusy(true); setError(''); try { await apiFetch('/api/question-bank', { method: 'POST', body: JSON.stringify({ prompt: prompt.trim() }) }); setPrompt(''); load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Question could not be created.') } finally { setBusy(false) } }
  return <div className="ad-directory-page"><PageHeader title="Question bank" description="Create and reuse questions while tracking their governance state." /><section className="ad-section ad-section--plain"><div className="ad-inline-create"><Input placeholder="New question prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} /><Button busy={busy} onClick={() => void create()}>Create draft question</Button></div><FormMessage>{error}</FormMessage>{items.length ? <div className="sb-table-wrap"><table className="sb-table"><thead><tr><th>Question</th><th>Type</th><th>Status</th></tr></thead><tbody>{items.map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.prompt ?? item.title ?? 'Question')}</td><td>{String(item.type ?? 'question')}</td><td>{String(item.reviewStatus ?? item.status ?? 'draft')}</td></tr>)}</tbody></table></div> : <p className="ad-empty-line">No questions yet. Create the first draft above.</p>}</section></div>
}

export function ContentReviewRoute({ slug }: { slug: string[] }) { if (!slug.length) return <ContentReviewDashboard />; if (slug[0] === 'question-bank') return <AuthorQuestionBank />; const contentId = slug[0] ?? ''; return <ContentReviewDetail contentId={contentId} update={slug[1] === 'update'} /> }
